# Generated by Django 5.0.1 on 2024-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.ImageField(upload_to='flags/')),
                ('hero', models.ImageField(upload_to='heros/')),
                ('country', models.CharField(max_length=256)),
                ('song', models.CharField(max_length=512)),
                ('placement', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
