# Generated by Django 5.0.1 on 2024-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.FileField(upload_to='flags/'),
        ),
    ]
