# Generated by Django 5.0.1 on 2024-05-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
